// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CyberThink
{
	public partial class Notes_ViewController : UIViewController
	{
		public Notes_ViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
