// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CyberThink
{
	public partial class ScrollViewTest : UIViewController
	{
		public ScrollViewTest (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            //scrollView.ContentSize = new CoreGraphics.CGSize(View.Frame.Width, View.Frame.Height + 1000);


           

            

            
           
            
        }

      
    }
}
